Поправил высоту ленты в инбоксе
lesha-dev/asana-ublock pull request #5
Opened 2023-10-12 08:42 UTC by gadzhiabakaribragimov-playrix

2023-10-12 10:54 UTC, lesha-dev approved these changes

2023-10-12 10:56 UTC, lesha-dev requested changes
Поправь конфликт с главной веткой, пожалуйста

2023-10-15 23:16 UTC, gadzhiabakaribragimov-playrix commented
> Поправь конфликт с главной веткой, пожалуйста

поправил

2023-10-16 06:03 UTC, lesha-dev approved these changes

2023-10-16 06:04 UTC, merged